/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    categories: Category;
    media: Media;
    classifieds: Classified;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
      classifieds: 'classifieds';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    classifieds: ClassifiedsSelect<false> | ClassifiedsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'shop-settings': ShopSetting;
    'image-settings': ImageSetting;
    'kleinanzeigen-settings': KleinanzeigenSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'shop-settings': ShopSettingsSelect<false> | ShopSettingsSelect<true>;
    'image-settings': ImageSettingsSelect<false> | ImageSettingsSelect<true>;
    'kleinanzeigen-settings': KleinanzeigenSettingsSelect<false> | KleinanzeigenSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles?: ('admin' | 'customer')[] | null;
  orders?: {
    docs?: (string | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (string | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (string | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (string | null) | User;
  customerEmail?: string | null;
  transactions?: (string | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  /**
   * Article number / SKU from Lexware or other sources. Used for sync and gallery import.
   */
  articleNumber?: string | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (string | VariantType)[] | null;
  variants?: {
    docs?: (string | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInUSDEnabled?: boolean | null;
  /**
   * Preis inkl. MwSt.
   */
  priceInUSD?: number | null;
  /**
   * Steuert, welche technischen Felder sichtbar sind. Optional für Produkte ohne spezifische Typ-Spezifikationen.
   */
  productType?:
    | ('tractor' | 'attachment' | 'construction' | 'schlegel' | 'frontladerZubehoer' | 'anhaenger' | 'excavator')
    | null;
  description_short?: string | null;
  description_long?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: string | Media;
        variantOption?: (string | null) | VariantOption;
        id?: string | null;
      }[]
    | null;
  layout?:
    | (
        | CallToActionBlock
        | ContentBlock
        | FormBlock
        | MediaBlock
        | BannerBlock
        | ArchiveBlock
        | CarouselBlock
        | ThreeItemGridBlock
        | YoutubeBlock
        | TechSpecsBlock
        | QuickSpecsBlock
        | ChecklistBlock
        | IconFeaturesBlock
      )[]
    | null;
  tractorSpecs?: {
    engine_type?: string | null;
    power_hp?: number | null;
    engine_cylinders?: number | null;
    engine_bore_mm?: number | null;
    engine_stroke_mm?: number | null;
    engine_displacement_cc?: number | null;
    engine_rated_rpm?: number | null;
    engine_max_torque_nm?: number | null;
    engine_max_torque_rpm?: number | null;
    battery_voltage_v?: number | null;
    battery_capacity_ah?: number | null;
    alternator_output_a?: number | null;
    trailer_socket?: ('none' | '7pin' | '13pin') | null;
    hydraulics_auto_depth_control?: boolean | null;
    hydraulics_position_control?: boolean | null;
    three_point_category?: ('I' | 'II' | 'III') | null;
    hydraulic_valves_count?: number | null;
    lift_capacity_kg?: number | null;
    brake_type?: string | null;
    brake_activation?: ('mechanical' | 'hydraulic') | null;
    parking_brake?: boolean | null;
    turning_circle_without_brakes_m?: number | null;
    turning_circle_with_brakes_m?: number | null;
    drive?: ('2wd' | '4wd') | null;
    clutch_type?: string | null;
    gearbox?: string | null;
    transmission_type?: string | null;
    min_speed_kmh?: number | null;
    min_speed_rpm?: number | null;
    max_speed_kmh?: number | null;
    max_speed_rpm?: number | null;
    tire_front?: string | null;
    tire_rear?: string | null;
    pto_speeds?: string | null;
    pto_type?: ('mechanical' | 'hydraulic') | null;
    steering_type?: ('mechanical' | 'hydraulic') | null;
    weight_kg?: number | null;
    wheelbase_mm?: number | null;
    length_mm?: number | null;
    width_mm?: number | null;
    height_mm?: number | null;
    ground_clearance_mm?: number | null;
  };
  attachmentSpecs?: {
    mounting?: ('3-punkt' | 'frontlader' | 'euroaufnahme') | null;
    capacity_l?: number | null;
    lower_link_attachment?: string | null;
    upper_link_attachment?: string | null;
    frame?: string | null;
    spreader_disc_diameter_cm?: number | null;
    dimensions_length_cm?: number | null;
    dimensions_width_cm?: number | null;
    dimensions_height_cm?: number | null;
    weight_kg?: number | null;
    work_speed_min_km_h?: number | null;
    work_speed_max_km_h?: number | null;
    ready_to_use?: boolean | null;
    required_hydraulic_flow_l_min?: number | null;
    requires_rear_pto?: boolean | null;
    compatible_hitch_category?: ('i' | 'ii' | 'iii') | null;
  };
  constructionSpecs?: {
    operating_weight_kg?: number | null;
    engine_power_hp?: number | null;
    bucket_capacity_m3?: number | null;
    max_reach_m?: number | null;
    road_legal?: boolean | null;
  };
  schlegelSpecs?: {
    model?: string | null;
    typology?: ('mulcher' | 'standardmulcher_heckanbau') | null;
    tractor_power_from_ps?: number | null;
    tractor_power_to_ps?: number | null;
    robustness_series?: ('leicht' | 'mittel' | 'schwer') | null;
    mounting_type?: ('feste_aufnahme' | 'handgefuehrte_verschiebung') | null;
    manual_shifting?: boolean | null;
    rotor_two_screws?: boolean | null;
    three_point_category?: ('kat1' | 'kat2' | 'kat1_und_2') | null;
    cardan_shaft_rotation?: ('standard' | 'rechtsdrehend' | 'linksdrehend') | null;
    manufacturing_country?: string | null;
    gearbox_integrated_freewheel?: boolean | null;
    belt_lateral_transmission?: number | null;
    cutting_width_cm?: number | null;
    max_wood_diameter_mm?: number | null;
    blade_count?: number | null;
    standard_tools?: ('schlegel' | 'hammermesser') | null;
    flail_weight_kg?: number | null;
    cutting_width_cm_detail?: number | null;
    counter_blade_rows?: number | null;
    hydraulic_piston_shifting?: boolean | null;
    support_roller?: boolean | null;
    wooden_pallet_included?: boolean | null;
    side_skids?: boolean | null;
    cardan_shaft_included?: boolean | null;
    cardan_shaft?: boolean | null;
    manual_included?: boolean | null;
    product_length_cm?: number | null;
    product_width_cm?: number | null;
    product_height_cm?: number | null;
    net_weight_kg?: number | null;
    packaging_type?: ('auf_palette' | 'ohne_palette') | null;
    packaging_length_cm?: number | null;
    packaging_width_cm?: number | null;
    packaging_height_cm?: number | null;
    total_weight_with_packaging_kg?: number | null;
    delivery_hydraulic_unloading_platform?: boolean | null;
    assembly_time_minutes?: number | null;
  };
  frontladerZubehoerSpecs?: {
    technicalData?: {
      width?: {
        value?: number | null;
        unit?: ('mm' | 'cm' | 'm') | null;
      };
      hydraulicCylinders?: {
        value?: number | null;
        unit?: 'Stk' | null;
      };
      requiresDwConnection?: boolean | null;
      weight?: {
        value?: number | null;
        unit?: 'kg' | null;
      };
      mounting?: 'euroaufnahme' | null;
      swivel?: ('hydraulisch' | 'vorlauf' | 'ruecklauf')[] | null;
      oilPressureTo?: {
        value?: number | null;
        unit?: 'bar' | null;
      };
      driveType?: ('manuell' | 'hydraulisch') | null;
      hydraulicPower?: {
        value?: number | null;
        unit?: ('l/min' | 'bar' | 'PS' | 'kW') | null;
      };
      tractorPowerMin?: {
        value?: number | null;
        unit?: ('PS' | 'kW') | null;
      };
      tractorPowerMax?: {
        value?: number | null;
        unit?: ('PS' | 'kW') | null;
      };
      rpmPerMinute?: {
        value?: number | null;
        unit?: 'U/min' | null;
      };
    };
    dimensions?: {
      height?: {
        value?: number | null;
        unit?: ('mm' | 'cm' | 'm') | null;
      };
      openingWidth?: {
        value?: number | null;
        unit?: ('mm' | 'cm' | 'm') | null;
      };
      packagingDimensions?: {
        length?: {
          value?: number | null;
          unit?: ('mm' | 'cm' | 'm') | null;
        };
        width?: {
          value?: number | null;
          unit?: ('mm' | 'cm' | 'm') | null;
        };
        height?: {
          value?: number | null;
          unit?: ('mm' | 'cm' | 'm') | null;
        };
        weight?: {
          value?: number | null;
          unit?: 'kg' | null;
        };
      };
    };
  };
  anhaengerSpecs?: {
    axle_configuration?: ('single_axle' | 'tandem_axle') | null;
    function?: 'three_side_tipper'[] | null;
    technology?: string | null;
    stvo_lighting?: ('yes' | 'no') | null;
    max_permitted_weight_kg?: number | null;
    can_be_derated?: ('yes' | 'no') | null;
    equipment?:
      | (
          | 'massive_verzinkte_bordwaende'
          | 'hoehen_verstellbare_deichsel'
          | 'verzurroesen'
          | 'gitteraufsatzbracke'
          | 'plane'
        )[]
      | null;
    delivery?: ('assembled' | 'final_assembly_required') | null;
    registration?: ('road_legal' | '100_kmh' | 'tuv_new')[] | null;
    height_adjustable_support_leg?: boolean | null;
    axle_type?: ('pendelachsen' | 'starrachse') | null;
    box_dimensions_inside?: string | null;
    box_dimensions_outside?: string | null;
    tires?: string | null;
    hitch?: {
      type?: ('kugelkopf' | 'ringzug') | null;
      ball_height_min_mm?: number | null;
      ball_height_max_mm?: number | null;
      eye_height_min_mm?: number | null;
      eye_height_max_mm?: number | null;
    };
  };
  excavatorSpecs?: {
    manufacturer?: string | null;
    model?: string | null;
    engine_type?: string | null;
    cooling_type?: string | null;
    engine_max_torque_nm?: number | null;
    engine_max_rpm?: number | null;
    fuel_tank_capacity_l?: number | null;
    starter_voltage_v?: number | null;
    max_speed_kmh?: number | null;
    max_gradeability_deg?: number | null;
    ground_pressure_kgf_cm2?: number | null;
    dimensions_lxbxh_mm?: string | null;
    track_dimensions_lxbxh_mm?: string | null;
    weight_kg?: number | null;
    hydraulic_oil_tank_capacity_l?: number | null;
    hydraulic_oil_type?: string | null;
    hydraulic_pump_type?: string | null;
    hydraulic_working_pressure_bar?: number | null;
    hydraulic_max_pressure_bar?: number | null;
    hydraulic_flow_l_min?: number | null;
    dig_depth_mm?: number | null;
    dump_height_mm?: number | null;
    reach_at_ground_mm?: number | null;
    bucket_breakout_force_kg?: number | null;
    swing_radius_deg?: string | null;
    swing_speed_rpm?: number | null;
    knickmatic_arm?: boolean | null;
    hydraulic_adjustable_track?: boolean | null;
    auxiliary_hydraulic_connection?: boolean | null;
  };
  /**
   * Use the default tax rate from Shop Settings. Uncheck to set a product-specific tax rate.
   */
  useShopTaxRate?: boolean | null;
  /**
   * Tax rate in % for this product (e.g. 19 for 19%). Only used when "Use shop tax rate" is unchecked.
   */
  taxRate?: number | null;
  /**
   * Preis ohne MwSt. Wird aus Bruttopreis berechnet oder füllt den Bruttopreis (je nach Steuersatz).
   */
  netPrice?: number | null;
  relatedProducts?: (string | Product)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * Kleinanzeigen für dieses Produkt
   */
  classifieds?: {
    docs?: (string | Classified)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  categories?: (string | Category)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  addedByPlugin?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: string;
  label: string;
  name: string;
  options?: {
    docs?: (string | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: string;
  _variantOptions_options_order?: string | null;
  variantType: string | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: string;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: string | Product;
  options: (string | VariantOption)[];
  inventory?: number | null;
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Apply the global image filter settings to this image. Uncheck to keep the original image.
   */
  applyFilter?: boolean | null;
  addedByPlugin?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  /**
   * Block über die gesamte Seitenbreite darstellen (kein Container).
   */
  fullWidth?: boolean | null;
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  publishedOn?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | CarouselBlock
    | ThreeItemGridBlock
    | BannerBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  /**
   * Block über die gesamte Seitenbreite darstellen (kein Container).
   */
  fullWidth?: boolean | null;
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  /**
   * Block über die gesamte Seitenbreite darstellen (kein Container).
   */
  fullWidth?: boolean | null;
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  /**
   * Block über die gesamte Seitenbreite darstellen (kein Container).
   */
  fullWidth?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  /**
   * Block über die gesamte Seitenbreite darstellen (kein Container).
   */
  fullWidth?: boolean | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  /**
   * Block über die gesamte Seitenbreite darstellen (kein Container).
   */
  fullWidth?: boolean | null;
  products?: (string | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  /**
   * Block über die gesamte Seitenbreite darstellen (kein Container).
   */
  fullWidth?: boolean | null;
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  /**
   * Block über die gesamte Seitenbreite darstellen (kein Container).
   */
  fullWidth?: boolean | null;
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YoutubeBlock".
 */
export interface YoutubeBlock {
  /**
   * Block über die gesamte Seitenbreite darstellen (kein Container).
   */
  fullWidth?: boolean | null;
  /**
   * z.B. https://www.youtube.com/watch?v=... oder https://youtu.be/...
   */
  url: string;
  title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'youtube';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TechSpecsBlock".
 */
export interface TechSpecsBlock {
  /**
   * Block über die gesamte Seitenbreite darstellen (kein Container).
   */
  fullWidth?: boolean | null;
  title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'techSpecs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuickSpecsBlock".
 */
export interface QuickSpecsBlock {
  /**
   * Block über die gesamte Seitenbreite darstellen (kein Container).
   */
  fullWidth?: boolean | null;
  specs?:
    | {
        icon:
          | 'engine'
          | 'drivetrain'
          | 'drivetrain-2'
          | 'mechanic'
          | 'weight'
          | 'spare-parts'
          | 'tractor'
          | 'wrench'
          | 'engineering'
          | 'technical-support'
          | 'delivery'
          | 'telephone'
          | 'part'
          | 'reduced'
          | 'car-engine'
          | 'whatsapp'
          | 'phone-call';
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quickSpecs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChecklistBlock".
 */
export interface ChecklistBlock {
  /**
   * Block über die gesamte Seitenbreite darstellen (kein Container).
   */
  fullWidth?: boolean | null;
  title?: string | null;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'checklist';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconFeaturesBlock".
 */
export interface IconFeaturesBlock {
  /**
   * Block über die gesamte Seitenbreite darstellen (kein Container).
   */
  fullWidth?: boolean | null;
  features?:
    | {
        icon:
          | 'engine'
          | 'drivetrain'
          | 'drivetrain-2'
          | 'mechanic'
          | 'weight'
          | 'spare-parts'
          | 'tractor'
          | 'wrench'
          | 'engineering'
          | 'technical-support'
          | 'delivery'
          | 'telephone'
          | 'part'
          | 'reduced'
          | 'car-engine'
          | 'whatsapp'
          | 'phone-call';
        headline: string;
        text?: string | null;
        enableLink?: boolean | null;
        link?: {
          label?: string | null;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'iconFeatures';
}
/**
 * Kleinanzeigen für Kleinanzeigen.de
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classifieds".
 */
export interface Classified {
  id: string;
  /**
   * Verknüpftes Produkt (Verbindung über Artikelnummer)
   */
  product?: (string | null) | Product;
  /**
   * Artikelnummer des verknüpften Produkts (automatisch befüllt)
   */
  articleNumber?: string | null;
  title: string;
  description: string;
  /**
   * Wird vor der Hauptbeschreibung eingefügt
   */
  description_prefix?: string | null;
  /**
   * Wird nach der Hauptbeschreibung eingefügt
   */
  description_suffix?: string | null;
  /**
   * Kleinanzeigen.de Kategorie (Volltext-Suche möglich)
   */
  category:
    | '210/241'
    | '210/216/sonstige_autos'
    | '210/216/alfa_romeo'
    | '210/216/audi'
    | '210/216/bmw'
    | '210/216/chevrolet'
    | '210/216/chrysler'
    | '210/216/citroen'
    | '210/216/dacia'
    | '210/216/daewoo'
    | '210/216/daihatsu'
    | '210/216/fiat'
    | '210/216/ford'
    | '210/216/honda'
    | '210/216/hyundai'
    | '210/216/jaguar'
    | '210/216/jeep'
    | '210/216/kia'
    | '210/216/lada'
    | '210/216/lancia'
    | '210/216/land_rover'
    | '210/216/lexus'
    | '210/216/mazda'
    | '210/216/mercedes_benz'
    | '210/216/mini'
    | '210/216/mitsubishi'
    | '210/216/nissan'
    | '210/216/opel'
    | '210/216/peugeot'
    | '210/216/porsche'
    | '210/216/renault'
    | '210/216/rover'
    | '210/216/saab'
    | '210/216/seat'
    | '210/216/skoda'
    | '210/216/smart'
    | '210/216/subaru'
    | '210/216/suzuki'
    | '210/216/tesla'
    | '210/216/toyota'
    | '210/216/trabant'
    | '210/216/volkswagen'
    | '210/216/volvo'
    | '210/223/sonstige_autoteile'
    | '210/223/auto_hifi_navigation'
    | '210/223/ersatz_reparaturteile'
    | '210/223/reifen_felgen'
    | '210/223/tuning_styling'
    | '210/223/werkzeug'
    | '210/211/andere'
    | '210/211/motorboote'
    | '210/211/segelboote'
    | '210/211/kleinboote'
    | '210/211/schlauchboote'
    | '210/211/jetski'
    | '210/211/bootstrailer'
    | '210/211/bootsliegeplaetze'
    | '210/211/bootszubehoer'
    | '210/217/weiteres'
    | '210/217/damen'
    | '210/217/herren'
    | '210/217/kinder'
    | '210/217/zubehoer'
    | '210/305/mofa'
    | '210/305/motorrad'
    | '210/305/roller'
    | '210/305/quad'
    | '210/306/teile'
    | '210/306/reifen_felgen'
    | '210/306/kleidung'
    | '210/276/andere'
    | '210/276/agrarfahrzeuge'
    | '210/276/anhaenger'
    | '210/276/baumaschinen'
    | '210/276/busse'
    | '210/276/lkw'
    | '210/276/sattelzugmaschinen_auflieger'
    | '210/276/stapler'
    | '210/276/traktoren'
    | '210/276/transporter'
    | '210/276/zubehoer'
    | '210/280'
    | '210/220/andere'
    | '210/220/alkoven'
    | '210/220/integrierter'
    | '210/220/kastenwagen'
    | '210/220/teilintegrierter'
    | '210/220/wohnwagen'
    | '297/298'
    | '297/288'
    | '297/289'
    | '297/290'
    | '297/293'
    | '297/291/sonstige'
    | '297/291/bau_handwerk'
    | '297/291/garten_landschaftsbau'
    | '297/291/haushaltshilfe'
    | '297/291/reingungsservice'
    | '297/291/reparaturen'
    | '297/291/wohnungsaufloesungen'
    | '297/292'
    | '297/294'
    | '297/295'
    | '297/296'
    | '231/256'
    | '231/286'
    | '231/254'
    | '231/287'
    | '231/252'
    | '231/255'
    | '231/257'
    | '231/251'
    | '161/168'
    | '161/172/sonstiges'
    | '161/172/cd_player'
    | '161/172/lautsprecher_kopfhoerer'
    | '161/172/mp3_player'
    | '161/172/radio_receiver'
    | '161/172/stereoanlagen'
    | '161/226'
    | '161/245/other'
    | '161/245/camera'
    | '161/245/lens'
    | '161/245/equipment'
    | '161/245/camera_and_equipment'
    | '161/173/sonstige'
    | '161/173/apple'
    | '161/173/google_handy'
    | '161/173/huawai_handy'
    | '161/173/htc_handy'
    | '161/173/lg_handy'
    | '161/173/motorola_handy'
    | '161/173/nokia_handy'
    | '161/173/samsung_handy'
    | '161/173/siemens_handy'
    | '161/173/sony_handy'
    | '161/173/xiaomi_handy'
    | '161/173/faxgeraete'
    | '161/173/telefone'
    | '161/176/sonstige'
    | '161/176/haushaltskleingeraete'
    | '161/176/herde_backoefen'
    | '161/176/kaffee_espressomaschinen'
    | '161/176/kuehlschraenke_gefriergeraete'
    | '161/176/spuelmaschinen'
    | '161/176/staubsauger'
    | '161/176/waschmaschinen_trockner'
    | '161/279/weitere'
    | '161/279/dsi_psp'
    | '161/279/playstation'
    | '161/279/xbox'
    | '161/279/wii'
    | '161/278'
    | '161/228'
    | '161/225/sonstiges'
    | '161/225/drucker_scanner'
    | '161/225/festplatten_laufwerke'
    | '161/225/gehaeuse'
    | '161/225/grafikkarten'
    | '161/225/kabel_adapter'
    | '161/225/mainboards'
    | '161/225/monitore'
    | '161/225/multimedia'
    | '161/225/netzwerk_modem'
    | '161/225/prozessor_cpu'
    | '161/225/speicher'
    | '161/225/software'
    | '161/225/tastatur_maus'
    | '161/285/weitere'
    | '161/285/ipad'
    | '161/285/kindle'
    | '161/285/samsung_tablets'
    | '161/175/weitere'
    | '161/175/dvdplayer_recorder'
    | '161/175/fernseher'
    | '161/175/tv_receiver'
    | '161/227/sonstige'
    | '161/227/dsi_psp'
    | '161/227/nintendo'
    | '161/227/playstation'
    | '161/227/xbox'
    | '161/227/wii'
    | '161/227/pc_spiele'
    | '17/18'
    | '17/236'
    | '17/22/sonstiges'
    | '17/22/hosen_jeans'
    | '17/22/kleider_roecke'
    | '17/22/shirts_tops'
    | '17/22/hemden'
    | '17/22/jacken_mantel'
    | '17/22/pullover_strickjacken'
    | '17/22/wasche'
    | '17/22/sportbekleidung'
    | '17/22/bademode'
    | '17/22/accessoires'
    | '17/22/kleidungspakete'
    | '17/19/sonstiges'
    | '17/19/ballerinas'
    | '17/19/halb_schnuerschuhe'
    | '17/19/hausschuhe'
    | '17/19/sandalen'
    | '17/19/outdoor_wanderschuhe'
    | '17/19/sneaker_sportschuhe'
    | '17/19/stiefel_stiefeletten'
    | '17/19/badeschuhe'
    | '17/258'
    | '17/21'
    | '17/237'
    | '17/25'
    | '17/20/sonstige'
    | '17/20/betten_wiegen'
    | '17/20/hochstuehle_laufstaelle'
    | '17/20/schraenke_kommoden'
    | '17/20/wickeltische_zubehoer'
    | '17/20/wippen_schaukeln'
    | '17/23/sonstiges'
    | '17/23/actionfiguren'
    | '17/23/babyspielzeug'
    | '17/23/barbie'
    | '17/23/dreirad'
    | '17/23/gesellschaftsspiele'
    | '17/23/holzspielzeug'
    | '17/23/lego_duplo'
    | '17/23/lernspielzeug'
    | '17/23/playmobil'
    | '17/23/puppen'
    | '17/23/spielzeug_autos'
    | '17/23/spielzeug_draussen'
    | '17/23/stofftiere'
    | '185/242'
    | '185/232'
    | '185/248'
    | '185/187'
    | '185/282'
    | '185/240'
    | '185/191'
    | '185/249'
    | '185/233'
    | '185/234/sonstige'
    | '185/234/ansichts_postkarten'
    | '185/234/autogramme'
    | '185/234/bierkruege_glaeser'
    | '185/234/briefmarken'
    | '185/234/comics'
    | '185/234/flaggen'
    | '185/234/muenzen'
    | '185/234/porzellan'
    | '185/234/puppen_puppenzubehoer'
    | '185/234/sammelbilder_sticker'
    | '185/234/sammelkartenspiele'
    | '185/234/ueberraschungseier'
    | '185/234/werbeartikel'
    | '185/230/sonstige'
    | '185/230/ballsport'
    | '185/230/camping'
    | '185/230/fitness'
    | '185/230/radsport'
    | '185/230/tanzen_laufen'
    | '185/230/wassersport'
    | '185/230/wintersport'
    | '185/250'
    | '185/189'
    | '80/87'
    | '80/91'
    | '80/93'
    | '80/246/weitere'
    | '80/246/bilder_poster'
    | '80/246/kerzen_kerzenhalter'
    | '80/246/spiegel'
    | '80/246/vasen'
    | '80/239/sonstige'
    | '80/239/bau_handwerk'
    | '80/239/garten_landschaftsbau'
    | '80/239/haushaltshilfe'
    | '80/239/reingungsservice'
    | '80/239/reparaturen'
    | '80/239/wohnungsaufloesungen'
    | '80/89/sonstige'
    | '80/89/blumentoepfe'
    | '80/89/dekoration'
    | '80/89/gartengeraete'
    | '80/89/gartenmoebel'
    | '80/89/pflanzen'
    | '80/90'
    | '80/84'
    | '80/86/sonstige'
    | '80/86/besteck'
    | '80/86/geschirr'
    | '80/86/glaeser'
    | '80/86/kuechengeraete'
    | '80/86/kuechenschraenke'
    | '80/86/stuehle'
    | '80/86/tische'
    | '80/82'
    | '80/81/sonstiges'
    | '80/81/betten'
    | '80/81/lattenroste'
    | '80/81/matratzen'
    | '80/81/nachttische'
    | '80/81/schraenke'
    | '80/88/sonstiges'
    | '80/88/regale'
    | '80/88/schraenke'
    | '80/88/sitzmoebel'
    | '80/88/sofas_sitzgarnituren'
    | '80/88/tische'
    | '80/88/tv_moebel'
    | '130/138/sonstige'
    | '130/138/aquarium'
    | '130/138/barsche'
    | '130/138/diskusfische'
    | '130/138/garnelen_krebse'
    | '130/138/koi'
    | '130/138/schnecken'
    | '130/138/wasserpflanzen'
    | '130/138/welse'
    | '130/134/sonstige'
    | '130/134/mischlinge'
    | '130/134/beagle'
    | '130/134/bernhardiner'
    | '130/134/border_collie'
    | '130/134/boxer'
    | '130/134/cocker_spaniel'
    | '130/134/collie'
    | '130/134/dackel'
    | '130/134/dalmatiner'
    | '130/134/dobermann'
    | '130/134/dogge'
    | '130/134/goldenretriever'
    | '130/134/husky'
    | '130/134/jack_russel_terrier'
    | '130/134/labrador'
    | '130/134/malteser'
    | '130/134/pudel'
    | '130/134/schaeferhund'
    | '130/134/spitz'
    | '130/134/terrier'
    | '130/136/sonstige'
    | '130/136/britisch_kurzhaar'
    | '130/136/hauskatze'
    | '130/136/maine_coon'
    | '130/136/siam'
    | '130/132/sonstige'
    | '130/132/hamster'
    | '130/132/hasen_kaninchen'
    | '130/132/maeuse_ratten'
    | '130/132/meerschweinchen'
    | '130/135'
    | '130/139/grosspferde'
    | '130/139/kleinpferde_ponys'
    | '130/133'
    | '130/283/entlaufen'
    | '130/283/gefunden'
    | '130/243'
    | '130/313/sonstiges'
    | '130/313/fische'
    | '130/313/hunde'
    | '130/313/katzen'
    | '130/313/kleintiere'
    | '130/313/pferde'
    | '130/313/reptilien'
    | '130/313/voegel'
    | '195/198'
    | '195/199/entire_accommodation'
    | '195/199/private_room'
    | '195/199/shared_room'
    | '195/196'
    | '195/275/kaufen'
    | '195/275/mieten'
    | '195/197/kaufen'
    | '195/197/mieten'
    | '195/277/kaufen'
    | '195/277/mieten'
    | '195/207/andere'
    | '195/207/baugrundstueck'
    | '195/207/garten'
    | '195/207/land_forstwirtschaft'
    | '195/208'
    | '195/205'
    | '195/203'
    | '195/238'
    | '102/118'
    | '102/111/weitere'
    | '102/111/bauhelfer'
    | '102/111/dachdecker'
    | '102/111/elektriker'
    | '102/111/fliesenleger'
    | '102/111/maler'
    | '102/111/maurer'
    | '102/111/produktionshelfer'
    | '102/111/schlosser'
    | '102/111/tischler'
    | '102/114/weitere'
    | '102/114/buchhalter'
    | '102/114/buerokauf'
    | '102/114/sachbearbeiter'
    | '102/114/sekretaer'
    | '102/110/weitere'
    | '102/110/barkeeper'
    | '102/110/hotelfach'
    | '102/110/zimmermaedchen'
    | '102/110/kellner'
    | '102/110/koch'
    | '102/110/kuechenhilfe'
    | '102/110/servicekraft'
    | '102/105'
    | '102/107'
    | '102/125'
    | '102/123/weitere'
    | '102/123/altenpfleger'
    | '102/123/artzhelfer'
    | '102/123/erzieher'
    | '102/123/krankenschwester'
    | '102/123/physiotherapeut'
    | '102/247/weitere'
    | '102/247/kraftfahrer'
    | '102/247/kurierfahrer'
    | '102/247/lagerhelfer'
    | '102/247/staplerfahrer'
    | '102/117/weitere'
    | '102/117/buchhalter'
    | '102/117/immobilienmakler'
    | '102/117/kauffrau'
    | '102/117/verkaeufer'
    | '102/109/weitere'
    | '102/109/designer_grafiker'
    | '102/109/friseur'
    | '102/109/haushaltshilfe'
    | '102/109/hausmeister'
    | '102/109/reinigungskraft'
    | '153/155'
    | '153/224/sonstiges'
    | '153/224/make_up'
    | '153/224/haarpflege'
    | '153/224/koerperpflege'
    | '153/224/handpflege'
    | '153/224/gesundheit'
    | '153/154/sonstige'
    | '153/154/anzuege'
    | '153/154/bademode'
    | '153/154/hemden_blusen'
    | '153/154/hochzeitsmode'
    | '153/154/hosen'
    | '153/154/jacken_maentel'
    | '153/154/jeans'
    | '153/154/kostueme_verkleidungen'
    | '153/154/pullover'
    | '153/154/roecke_kleider'
    | '153/154/shirts_tops'
    | '153/154/shorts'
    | '153/154/sportbekleidung'
    | '153/154/umstandsmode'
    | '153/159/sonstiges'
    | '153/159/ballerinas'
    | '153/159/halb_schnuerschuhe'
    | '153/159/hausschuhe'
    | '153/159/outdoor_wanderschuhe'
    | '153/159/pumps'
    | '153/159/sandalen'
    | '153/159/sneaker_sportschuhe'
    | '153/159/stiefel'
    | '153/160/sonstige'
    | '153/160/anzuege'
    | '153/160/bademode'
    | '153/160/hemden'
    | '153/160/hochzeitsmode'
    | '153/160/hosen'
    | '153/160/jacken_maentel'
    | '153/160/jeans'
    | '153/160/kostueme_verkleidungen'
    | '153/160/pullover'
    | '153/160/shirts'
    | '153/160/shorts'
    | '153/160/sportbekleidung'
    | '153/158/sonstiges'
    | '153/158/halb_schnuerschuhe'
    | '153/158/hausschuhe'
    | '153/158/sandalen'
    | '153/158/sneaker_sportschuhe'
    | '153/158/stiefel'
    | '153/158/outdoor_wanderschuhe'
    | '153/156/sonstiges'
    | '153/156/muetzen_schals_handschuhe'
    | '153/156/sonnenbrillen'
    | '153/156/taschen_rucksaecke'
    | '153/157/schmuck'
    | '153/157/uhren'
    | '73/75'
    | '73/76'
    | '73/76/antiquarische_buecher'
    | '73/76/kinderbuecher'
    | '73/76/krimis_thriller'
    | '73/76/kunst_kultur'
    | '73/76/sachbuecher'
    | '73/76/science_fiction'
    | '73/76/unterhaltungsliteratur'
    | '73/76/zeitgenoessische_literatur_klassiker'
    | '73/76/zeitschriften'
    | '73/281'
    | '73/284'
    | '73/77'
    | '73/79'
    | '73/78'
    | '73/74'
    | '400/401'
    | '235/270'
    | '235/269'
    | '235/260'
    | '235/265'
    | '235/263'
    | '235/264'
    | '235/262'
    | '235/268'
    | '235/261'
    | '235/271'
    | '235/267'
    | '235/266'
    | '272/273'
    | '272/274'
    | '272/192';
  /**
   * Plattform-spezifische Attribute als Schlüssel-Wert-Paare
   */
  special_attributes?:
    | {
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  type?: ('OFFER' | 'WANTED') | null;
  /**
   * Preis in Euro als ganzzahliger Wert (z.B. 119 = 119 €)
   */
  price?: number | null;
  price_type?: ('FIXED' | 'NEGOTIABLE' | 'GIVE_AWAY' | 'NOT_APPLICABLE') | null;
  shipping_type?: ('PICKUP' | 'SHIPPING' | 'NOT_APPLICABLE') | null;
  shipping_costs?: number | null;
  shipping_options?:
    | {
        option: string;
        id?: string | null;
      }[]
    | null;
  sell_directly?: boolean | null;
  /**
   * Maximal 10 Bilder (Limit von Kleinanzeigen.de)
   */
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  contact?: {
    name?: string | null;
    street?: string | null;
    zipcode?: string | null;
    location?: string | null;
    phone?: string | null;
  };
  /**
   * Anzahl der Tage zwischen automatischen Wiederveröffentlichungen
   */
  republication_interval?: number | null;
  /**
   * Anzahl erfolgreicher Veröffentlichungen (wird automatisch gepflegt)
   */
  repost_count?: number | null;
  /**
   * Anzahl automatischer Preisreduzierungen (wird automatisch gepflegt)
   */
  price_reduction_count?: number | null;
  auto_price_reduction?: {
    /**
     * Preis bei Wiederveröffentlichungen automatisch senken
     */
    enabled?: boolean | null;
    /**
     * PERCENTAGE = % des Preises, FIXED = absoluter Betrag
     */
    strategy?: ('PERCENTAGE' | 'FIXED') | null;
    /**
     * Für PERCENTAGE: Prozentwert (z.B. 10 = 10%). Für FIXED: Währungsbetrag.
     */
    amount?: number | null;
    /**
     * Preisuntergrenze (0 = kein Minimum)
     */
    min_price?: number | null;
    /**
     * Anzahl Wiederveröffentlichungen vor erster Preisreduzierung
     */
    delay_reposts?: number | null;
    /**
     * Tage nach Veröffentlichung vor erster Preisreduzierung
     */
    delay_days?: number | null;
  };
  /**
   * Ob die Anzeige auf der Plattform aktiv ist
   */
  active?: boolean | null;
  /**
   * Wird durch die externe Schnittstelle befüllt
   */
  kleinanzeigen_id?: number | null;
  /**
   * ISO-8601 Zeitstempel, wird durch die externe Schnittstelle befüllt
   */
  kleinanzeigen_created_on?: string | null;
  /**
   * Interner Hash zur Änderungserkennung
   */
  content_hash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'stripe' | null;
  stripe?: {
    customerID?: string | null;
    paymentIntentID?: string | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (string | null) | User;
  customerEmail?: string | null;
  order?: (string | null) | Order;
  cart?: (string | null) | Cart;
  amount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (string | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  customer?: (string | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'classifieds';
        value: string | Classified;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: string | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: string | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: string | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  applyFilter?: T;
  addedByPlugin?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classifieds_select".
 */
export interface ClassifiedsSelect<T extends boolean = true> {
  product?: T;
  articleNumber?: T;
  title?: T;
  description?: T;
  description_prefix?: T;
  description_suffix?: T;
  category?: T;
  special_attributes?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  type?: T;
  price?: T;
  price_type?: T;
  shipping_type?: T;
  shipping_costs?: T;
  shipping_options?:
    | T
    | {
        option?: T;
        id?: T;
      };
  sell_directly?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        name?: T;
        street?: T;
        zipcode?: T;
        location?: T;
        phone?: T;
      };
  republication_interval?: T;
  repost_count?: T;
  price_reduction_count?: T;
  auto_price_reduction?:
    | T
    | {
        enabled?: T;
        strategy?: T;
        amount?: T;
        min_price?: T;
        delay_reposts?: T;
        delay_days?: T;
      };
  active?: T;
  kleinanzeigen_id?: T;
  kleinanzeigen_created_on?: T;
  content_hash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  articleNumber?: T;
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  productType?: T;
  description_short?: T;
  description_long?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        youtube?: T | YoutubeBlockSelect<T>;
        techSpecs?: T | TechSpecsBlockSelect<T>;
        quickSpecs?: T | QuickSpecsBlockSelect<T>;
        checklist?: T | ChecklistBlockSelect<T>;
        iconFeatures?: T | IconFeaturesBlockSelect<T>;
      };
  tractorSpecs?:
    | T
    | {
        engine_type?: T;
        power_hp?: T;
        engine_cylinders?: T;
        engine_bore_mm?: T;
        engine_stroke_mm?: T;
        engine_displacement_cc?: T;
        engine_rated_rpm?: T;
        engine_max_torque_nm?: T;
        engine_max_torque_rpm?: T;
        battery_voltage_v?: T;
        battery_capacity_ah?: T;
        alternator_output_a?: T;
        trailer_socket?: T;
        hydraulics_auto_depth_control?: T;
        hydraulics_position_control?: T;
        three_point_category?: T;
        hydraulic_valves_count?: T;
        lift_capacity_kg?: T;
        brake_type?: T;
        brake_activation?: T;
        parking_brake?: T;
        turning_circle_without_brakes_m?: T;
        turning_circle_with_brakes_m?: T;
        drive?: T;
        clutch_type?: T;
        gearbox?: T;
        transmission_type?: T;
        min_speed_kmh?: T;
        min_speed_rpm?: T;
        max_speed_kmh?: T;
        max_speed_rpm?: T;
        tire_front?: T;
        tire_rear?: T;
        pto_speeds?: T;
        pto_type?: T;
        steering_type?: T;
        weight_kg?: T;
        wheelbase_mm?: T;
        length_mm?: T;
        width_mm?: T;
        height_mm?: T;
        ground_clearance_mm?: T;
      };
  attachmentSpecs?:
    | T
    | {
        mounting?: T;
        capacity_l?: T;
        lower_link_attachment?: T;
        upper_link_attachment?: T;
        frame?: T;
        spreader_disc_diameter_cm?: T;
        dimensions_length_cm?: T;
        dimensions_width_cm?: T;
        dimensions_height_cm?: T;
        weight_kg?: T;
        work_speed_min_km_h?: T;
        work_speed_max_km_h?: T;
        ready_to_use?: T;
        required_hydraulic_flow_l_min?: T;
        requires_rear_pto?: T;
        compatible_hitch_category?: T;
      };
  constructionSpecs?:
    | T
    | {
        operating_weight_kg?: T;
        engine_power_hp?: T;
        bucket_capacity_m3?: T;
        max_reach_m?: T;
        road_legal?: T;
      };
  schlegelSpecs?:
    | T
    | {
        model?: T;
        typology?: T;
        tractor_power_from_ps?: T;
        tractor_power_to_ps?: T;
        robustness_series?: T;
        mounting_type?: T;
        manual_shifting?: T;
        rotor_two_screws?: T;
        three_point_category?: T;
        cardan_shaft_rotation?: T;
        manufacturing_country?: T;
        gearbox_integrated_freewheel?: T;
        belt_lateral_transmission?: T;
        cutting_width_cm?: T;
        max_wood_diameter_mm?: T;
        blade_count?: T;
        standard_tools?: T;
        flail_weight_kg?: T;
        cutting_width_cm_detail?: T;
        counter_blade_rows?: T;
        hydraulic_piston_shifting?: T;
        support_roller?: T;
        wooden_pallet_included?: T;
        side_skids?: T;
        cardan_shaft_included?: T;
        cardan_shaft?: T;
        manual_included?: T;
        product_length_cm?: T;
        product_width_cm?: T;
        product_height_cm?: T;
        net_weight_kg?: T;
        packaging_type?: T;
        packaging_length_cm?: T;
        packaging_width_cm?: T;
        packaging_height_cm?: T;
        total_weight_with_packaging_kg?: T;
        delivery_hydraulic_unloading_platform?: T;
        assembly_time_minutes?: T;
      };
  frontladerZubehoerSpecs?:
    | T
    | {
        technicalData?:
          | T
          | {
              width?:
                | T
                | {
                    value?: T;
                    unit?: T;
                  };
              hydraulicCylinders?:
                | T
                | {
                    value?: T;
                    unit?: T;
                  };
              requiresDwConnection?: T;
              weight?:
                | T
                | {
                    value?: T;
                    unit?: T;
                  };
              mounting?: T;
              swivel?: T;
              oilPressureTo?:
                | T
                | {
                    value?: T;
                    unit?: T;
                  };
              driveType?: T;
              hydraulicPower?:
                | T
                | {
                    value?: T;
                    unit?: T;
                  };
              tractorPowerMin?:
                | T
                | {
                    value?: T;
                    unit?: T;
                  };
              tractorPowerMax?:
                | T
                | {
                    value?: T;
                    unit?: T;
                  };
              rpmPerMinute?:
                | T
                | {
                    value?: T;
                    unit?: T;
                  };
            };
        dimensions?:
          | T
          | {
              height?:
                | T
                | {
                    value?: T;
                    unit?: T;
                  };
              openingWidth?:
                | T
                | {
                    value?: T;
                    unit?: T;
                  };
              packagingDimensions?:
                | T
                | {
                    length?:
                      | T
                      | {
                          value?: T;
                          unit?: T;
                        };
                    width?:
                      | T
                      | {
                          value?: T;
                          unit?: T;
                        };
                    height?:
                      | T
                      | {
                          value?: T;
                          unit?: T;
                        };
                    weight?:
                      | T
                      | {
                          value?: T;
                          unit?: T;
                        };
                  };
            };
      };
  anhaengerSpecs?:
    | T
    | {
        axle_configuration?: T;
        function?: T;
        technology?: T;
        stvo_lighting?: T;
        max_permitted_weight_kg?: T;
        can_be_derated?: T;
        equipment?: T;
        delivery?: T;
        registration?: T;
        height_adjustable_support_leg?: T;
        axle_type?: T;
        box_dimensions_inside?: T;
        box_dimensions_outside?: T;
        tires?: T;
        hitch?:
          | T
          | {
              type?: T;
              ball_height_min_mm?: T;
              ball_height_max_mm?: T;
              eye_height_min_mm?: T;
              eye_height_max_mm?: T;
            };
      };
  excavatorSpecs?:
    | T
    | {
        manufacturer?: T;
        model?: T;
        engine_type?: T;
        cooling_type?: T;
        engine_max_torque_nm?: T;
        engine_max_rpm?: T;
        fuel_tank_capacity_l?: T;
        starter_voltage_v?: T;
        max_speed_kmh?: T;
        max_gradeability_deg?: T;
        ground_pressure_kgf_cm2?: T;
        dimensions_lxbxh_mm?: T;
        track_dimensions_lxbxh_mm?: T;
        weight_kg?: T;
        hydraulic_oil_tank_capacity_l?: T;
        hydraulic_oil_type?: T;
        hydraulic_pump_type?: T;
        hydraulic_working_pressure_bar?: T;
        hydraulic_max_pressure_bar?: T;
        hydraulic_flow_l_min?: T;
        dig_depth_mm?: T;
        dump_height_mm?: T;
        reach_at_ground_mm?: T;
        bucket_breakout_force_kg?: T;
        swing_radius_deg?: T;
        swing_speed_rpm?: T;
        knickmatic_arm?: T;
        hydraulic_adjustable_track?: T;
        auxiliary_hydraulic_connection?: T;
      };
  useShopTaxRate?: T;
  taxRate?: T;
  netPrice?: T;
  relatedProducts?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  classifieds?: T;
  categories?: T;
  generateSlug?: T;
  slug?: T;
  addedByPlugin?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YoutubeBlock_select".
 */
export interface YoutubeBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  url?: T;
  title?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TechSpecsBlock_select".
 */
export interface TechSpecsBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  title?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuickSpecsBlock_select".
 */
export interface QuickSpecsBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  specs?:
    | T
    | {
        icon?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChecklistBlock_select".
 */
export interface ChecklistBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  title?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconFeaturesBlock_select".
 */
export interface IconFeaturesBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  features?:
    | T
    | {
        icon?: T;
        headline?: T;
        text?: T;
        enableLink?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  stripe?:
    | T
    | {
        customerID?: T;
        paymentIntentID?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Currency and tax rate for the shop. Used to compute net/gross prices on products.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings".
 */
export interface ShopSetting {
  id: string;
  /**
   * Shop display and checkout currency.
   */
  currency: 'EUR' | 'USD' | 'CHF' | 'GBP';
  /**
   * Default tax rate in percent (e.g. 19 for 19%). Used to calculate net from gross and vice versa on products.
   */
  taxRate: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure global image processing filters for consistent product image styling.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-settings".
 */
export interface ImageSetting {
  id: string;
  /**
   * Enable automatic image processing for all uploaded images.
   */
  enabled?: boolean | null;
  /**
   * Adjust these settings to create a consistent visual style for all product images.
   */
  filters?: {
    /**
     * Image brightness percentage (100 = original).
     */
    brightness?: number | null;
    /**
     * Image contrast percentage (100 = original).
     */
    contrast?: number | null;
    /**
     * Color saturation percentage (100 = original).
     */
    saturation?: number | null;
    /**
     * Apply a color tint to warm up or cool down images.
     */
    tint?: {
      enabled?: boolean | null;
      /**
       * Hex color code for the tint (e.g., #FFAA44 for warm, #4488FF for cool).
       */
      color?: string | null;
      /**
       * Tint intensity percentage.
       */
      intensity?: number | null;
    };
    /**
     * Apply sharpening to enhance image clarity.
     */
    sharpen?: {
      enabled?: boolean | null;
      /**
       * Sharpening intensity (higher = sharper).
       */
      sigma?: number | null;
    };
    /**
     * Add a subtle dark vignette to focus attention on the center.
     */
    vignette?: {
      enabled?: boolean | null;
      /**
       * Vignette intensity percentage.
       */
      intensity?: number | null;
    };
  };
  /**
   * Default state for "Apply Filter" checkbox when users upload images. Can be disabled per-upload.
   */
  defaultApplyFilter?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Standardwerte für neue Kleinanzeigen. Werden automatisch vorausgefüllt und können pro Anzeige überschrieben werden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kleinanzeigen-settings".
 */
export interface KleinanzeigenSetting {
  id: string;
  /**
   * Wird in Anzeigen als Öffnungszeiten angezeigt (Freitext).
   */
  opening_hours?: string | null;
  /**
   * Wird als Standardbeschreibung bei neuen Kleinanzeigen vorausgefüllt.
   */
  description_template?: string | null;
  contact?: {
    name?: string | null;
    street?: string | null;
    zipcode?: string | null;
    location?: string | null;
    phone?: string | null;
  };
  automation?: {
    /**
     * Anzahl der Tage zwischen automatischen Wiederveröffentlichungen.
     */
    republication_interval?: number | null;
    auto_price_reduction_enabled?: boolean | null;
    auto_price_reduction_strategy?: ('PERCENTAGE' | 'FIXED') | null;
    /**
     * Für PERCENTAGE: Prozentwert (z.B. 10 = 10%). Für FIXED: Währungsbetrag.
     */
    auto_price_reduction_amount?: number | null;
    auto_price_reduction_min_price?: number | null;
    /**
     * Anzahl Wiederveröffentlichungen vor erster Preisreduzierung.
     */
    auto_price_reduction_delay_reposts?: number | null;
    /**
     * Tage nach Veröffentlichung vor erster Preisreduzierung.
     */
    auto_price_reduction_delay_days?: number | null;
  };
  shipping?: {
    shipping_type?: ('PICKUP' | 'SHIPPING' | 'NOT_APPLICABLE') | null;
    shipping_costs?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings_select".
 */
export interface ShopSettingsSelect<T extends boolean = true> {
  currency?: T;
  taxRate?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-settings_select".
 */
export interface ImageSettingsSelect<T extends boolean = true> {
  enabled?: T;
  filters?:
    | T
    | {
        brightness?: T;
        contrast?: T;
        saturation?: T;
        tint?:
          | T
          | {
              enabled?: T;
              color?: T;
              intensity?: T;
            };
        sharpen?:
          | T
          | {
              enabled?: T;
              sigma?: T;
            };
        vignette?:
          | T
          | {
              enabled?: T;
              intensity?: T;
            };
      };
  defaultApplyFilter?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kleinanzeigen-settings_select".
 */
export interface KleinanzeigenSettingsSelect<T extends boolean = true> {
  opening_hours?: T;
  description_template?: T;
  contact?:
    | T
    | {
        name?: T;
        street?: T;
        zipcode?: T;
        location?: T;
        phone?: T;
      };
  automation?:
    | T
    | {
        republication_interval?: T;
        auto_price_reduction_enabled?: T;
        auto_price_reduction_strategy?: T;
        auto_price_reduction_amount?: T;
        auto_price_reduction_min_price?: T;
        auto_price_reduction_delay_reposts?: T;
        auto_price_reduction_delay_days?: T;
      };
  shipping?:
    | T
    | {
        shipping_type?: T;
        shipping_costs?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}